# Generated by Django 5.1.1 on 2024-11-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chekout',
            old_name='quantity_id',
            new_name='quantity',
        ),
    ]
