# Generated by Django 5.1.1 on 2024-11-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
